
FROM python:3.12-slim

WORKDIR /app


RUN apt-get update && apt-get install -y --no-install-recommends \
    netcat-openbsd \
    curl \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY flow.py .
COPY wait-for-services.sh /wait-for-services.sh
RUN chmod +x /wait-for-services.sh


ENTRYPOINT ["/wait-for-services.sh"]
CMD ["python", "flow.py"]