version: '3.8'

services:
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
    networks:
      - celery_network

  spanner_emulator:
    image: gcr.io/cloud-spanner-emulator/emulator:latest
    container_name: spanner_emulator
    ports:
      - "9010:9010"  # Puerto gRPC
      - "9020:9020"  # Puerto REST
    networks:
      - celery_network

  spanner_init:
    build:
      context: ./initSpanner
      dockerfile: Dockerfile.spanner  
    container_name: spanner_init
    depends_on:
      - spanner_emulator
    environment:
      - SPANNER_EMULATOR_HOST=spanner_emulator:9010
    networks:
      - celery_network
  


  celery_worker:
    image: python:3.12-slim  
    container_name: celery_worker
    depends_on:
      - redis
      - spanner_init
      - localstack
    environment:
      - REDIS_HOST=redis
      - SPANNER_EMULATOR_HOST=spanner_emulator:9010 
      - URL_API_CUSTOMERS=http://customers_api:8001
      - URL_API_TRANSACTIONS=http://transactions_api:8002
      - LOCALSTACK_HOST=localstack
    command: celery -A worker.generation worker --loglevel=info
    volumes:
      - .:/app
    networks:
      - celery_network
    build:
      context: ./worker
      dockerfile: Dockerfile.celery

  
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" 
    environment:
      - DEBUG=1
      - SERVICES=s3 
    volumes:
      - ./init-scripts:/etc/localstack/init/ready.d 
      - ${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack  
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - celery_network

  runflow:
    build:
      context: ./runflow 
      dockerfile: Dockerfile.flow 
    container_name: runflow
    depends_on:
      customers_api:
        condition: service_healthy
      transactions_api:
        condition: service_healthy
    networks:
      - celery_network 
    environment:
      - REDIS_HOST=redis
    restart: on-failure
    entrypoint: /wait-for-services.sh
  customers_api:
    build:
      context: ./customersAPI
      dockerfile: Dockerfile
    container_name: customers_api
    ports:
      - "8001:8001"
    environment:
      - SPANNER_EMULATOR_HOST=spanner_emulator:9010 
    networks:
      - celery_network
    depends_on:
      - spanner_init 
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 60s
      timeout: 60s
      retries: 1
      start_period: 60s 

  transactions_api:
    build:
      context: ./transactionsAPI
      dockerfile: Dockerfile
    container_name: transactions_api
    ports:
      - "8002:8002"
    environment:
      - SPANNER_EMULATOR_HOST=spanner_emulator:9010  
    networks:
      - celery_network
    depends_on:
      - spanner_init 
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 60s
      timeout: 60s
      retries: 1
      start_period: 60s 


networks:
  celery_network:
    driver: bridge
