FROM google/cloud-sdk:latest

# Instalar herramientas adicionales
RUN apt-get update && apt-get install -y \
    dnsutils \ 
    && rm -rf /var/lib/apt/lists/*

# Copiar el script de inicialización
COPY init_spanner.sh /app/init_spanner.sh

# Establecer el directorio de trabajo
WORKDIR /app

# Dar permisos de ejecución al script
RUN chmod +x /app/init_spanner.sh

# Comando para ejecutar el script
CMD ["./init_spanner.sh"]