# Usa una imagen base de Python oficial
FROM python:3.12-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo de requisitos e instala las dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el script gencli.py al contenedor
COPY init_spanner.py .

# Comando por defecto al ejecutar el contenedor
CMD ["python", "init_spanner.py"]